services:
  # Developement Service
  virtual-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - /app/node_modules
      
    ports:
      - "3001:3000"
      
    environment:
      - NODE_ENV=developement
      
   # Producton Service